### ISSUE TITLE
DB 연결

### ISSUE THREAD

**Issue by gitagita** [gitagita/umanshi#1]
## 이슈 내용
DB 연결하기

## 테스트 경로
http://localhost:3000/api

## TODO
- [x] env 파일 생성 및 환경 변수 설정
- [x] app.js 파일 생성
- [x] 테이블 조회 api 생성해서 DB 연결 확인
